services:
  app:
    build: ./app
    expose:
      - "3000"
    depends_on:
      - databaseA
      - databaseB
    restart: on-failure

  app2:
    build: ./app
    expose:
      - "3000"
    depends_on:
      - databaseA
      - databaseB
    restart: on-failure

  app3:
    build: ./app
    expose:
      - "3000"
    depends_on:
      - databaseA
      - databaseB
    restart: on-failure

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
      - app2
      - app3
    restart: on-failure

  databaseA:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: proyecto
    restart: on-failure

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8080:80"
    restart: on-failure
    environment:
      PMA_HOST: databaseA
      MYSQL_ROOT_PASSWORD: root

  databaseB:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: proyecto
    restart: on-failure

  phpmyadminB:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8081:80"
    restart: on-failure
    environment:
      PMA_HOST: databaseB
      MYSQL_ROOT_PASSWORD: root
